name: fast-forward merge on label (no personal access token)

on:
  pull_request:
    types: [labeled]

jobs:
  echo-base-head-ref:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Ref: ${{ github.head_ref }}"

  fast-forward-merge:
    if: github.event.label.name == 'fast-forward-no-token'
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Payload
        run: |
          echo "Event Payload:"
          echo "${{ toJson(github.event) }}"
      - name: Fast Forward PR
        uses: onee-only/ff-merge@main
        with:
          allowed-roles: '["admin"]'
          comment: "always"
          merge: true
