name: fast-forward merge on label

on:
  pull_request:
    types: [labeled]

jobs:
  echo-base-head-ref:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Ref: ${{ github.head_ref }}"

  fast-forward-merge:
    if: github.event.label.name == 'fast-forward'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fast Forward PR
        uses: onee-only/ff-merge@main
        with:
          allowed-roles: '["maintain"]'
          comment: "always"
          merge: true
          GITHUB_TOKEN: ${{ secrets.FAST_FORWARD_GITHUB_TOKEN }}
